theme = "sobrio"

[editor]
color-modes = true
cursorline = true
line-number = "relative"
bufferline = "multiple"
# rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "â”‚"

[editor.lsp]
display-messages = true

[keys.normal]
C-o = ":config-open"
C-q = ":quit"
C-r = ":config-reload"
D = ["kill_to_line_end"]
esc = ["collapse_selection", "normal_mode"]
F11 = ":tree-sitter-scopes"
F12 = ":tree-sitter-subtree"
F4 = ":buffer-close"
ret = ["move_line_down", "goto_first_nonwhitespace"]
S-tab = ":buffer-previous"
tab = ":buffer-next"

[keys.select]
F9 = ":pipe sort"
